name: Snazzy LookML Linter
author:
description: Lint LookML Projects and create Pull Request reviews with linting violations.

inputs:
  configFile:
    description: 'path to config file'
    required: true
    default: ${{ github.workspace }}/.github/config.yaml
  filepaths:
    description: 'list of files to lint (using output of tj-actions/changed-files action in workflow)'
    required: false
    default: null

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.configFile }}
