- rule: field_requires_description
  severity: warning
- rule: view_with_many_fields_requires_fields_hidden_by_default
  severity: warning
- rule: view_with_dimensions_and_measures_has_one_primary_key
  severity: error
- rule: dimension_group_of_type_time_requires_datatype
  severity: warning
- rule: dimension_group_of_type_time_requires_timeframes
  severity: warning
- rule: explore_joins_require_relationship
  severity: warning
- rule: explore_requires_description
  severity: warning
- rule: explore_joins_contain_many_to_many_relationship
  severity: warning
- rule: explore_requires_label
  severity: warning
- rule: field_name_is_snake_case
  severity: warning
- rule: view_name_is_snake_case
  severity: warning
- rule: view_requires_label
  severity: warning
- rule: dimension_group_name_ends_with_date_time_or_day_pt
  severity: warning
- rule: yesno_field_label_contains_yesno
  severity: warning
- rule: field_sql_html_requires_user_attribute_when_search_terms_found_exact
  severity: ignore
  param_sets:
    - user_attribute: test
      search_terms:
        - a
          b
          c
    - user_attribute: test2
      search_terms:
        - x
          y
